<?php
/**
 * Страница "Содержание".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Editor "TinyMCE"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Web-based platform independent JavaScript HTML WYSIWYG editor. The main features of the editor include: support for themes / templates, language support and the ability to connect modules (plugins).</p>
    <p>Website: <a target="_blank" href="https://www.tiny.cloud">https://www.tiny.cloud</a></p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Customizing Editor "TinyMCE"</a></li>
    </ul>
</article>