<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Редактор "TinyMCE"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Платформонезависимый JavaScript HTML WYSIWYG редактор на основе Web. К основным характеристикам редактора относятся: поддержка тем/шаблонов, языковая поддержка и возможность подключения модулей (плагинов)</p>
    <p>Сайт: <a target="_blank" href="https://www.tiny.cloud">https://www.tiny.cloud</a></p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Настройка редактора "TinyMCE"</a></li>
    </ul>
</article>